### ISSUE TITLE
Complex is not `repr(C)`

### ISSUE THREAD

**Issue by bluss** [stainless-steel/blas#22]
The issue about complex is a bit tricky. In practice there is no problem at all; its memory layout is compatible with C complex, so using `&num::Complex<f64>` where a pointer to c complex is expected, is completely fine.

https://github.com/rust-num/num/issues/79

However it is our common interest that the linked issue is resolved in some way.

**Comment by IvanUkhov** [comment]
[As far as I understand](https://github.com/rust-lang/libc/issues/355), the main problem is when complex numbers are passed by value. All functions of this kind in both `blas` and `lapack` are currently broken on certain platforms, and it cannot be solved without an adequate support from the compiler.

I actually wanted to open an issue here and in `lapack` to warn about the current state of functions working with complex numbers. It should perhaps be also mentioned in the documentation.

**Comment by IvanUkhov** [comment]
@bluss, I guess this issue can be closed now since `Complex` already has `#[repr(C)]`, right? Regarding the concern that I expressed in my comment, I’ve just realized that neither CBLAS nor LAPACKE has functions taking complex numbers by value. Even when the argument is a complex scalar and could in principle be taken by value, it’s still taken by reference. The conclusion is that there is no dangar in using any of the complex functions provided by the `blas` and `lapack` crates. Does it sound right to you?

**Comment by bluss** [comment]
Yes, sorry for not coming back to this issue. That's the conclusion of the repr(C) on complex pr, that it is only relevant to memory layout compatibility.

**Comment by IvanUkhov** [comment]
I close this then.

And here is an update on what I wrote before. I’ve actually found several functions in LAPACKE that do take complex numbers by value. Here they are:

* LAPACKE_[c|z]larfx,
* LAPACKE_[c|z]laset,
* LAPACKE_[c|z]tfsm,
* LAPACKE_[c|z]syr,
* LAPACKE_[c|z]larfx_work,
* LAPACKE_[c|z]laset_work,
* LAPACKE_[c|z]tfsm_work, and
* LAPACKE_[c|z]syr_work.

So these ones are not safe to use.
