### ISSUE TITLE
Eliminate CBLAS

### ISSUE THREAD

**Issue by cmr** [stainless-steel/blas#8]
Calling through CBLAS and not the Fortran interfaces adds an unavoidable function call overhead that is completely unnecessary. Switch over to the Fortran interfaces.

**Comment by IvanUkhov** [comment]
@cmr, I have added the Fortran interface to `libblas-sys`.

**Comment by IvanUkhov** [comment]
Speaking about switching from C to Fortran, I think the layout/order parameter should go. If somebody wants to work with the row-major order, they should pay this price explicitly in their own code.

**Comment by cmr** [comment]
I am not so sure about that, since all it does is change loop order usually.

**Comment by IvanUkhov** [comment]
But that’s the point: the Fortran routines have only one order. They do not even have that parameter, and they always assume the column-major order. So, as far as I understand, the C wrappers allocate additional memory and transpose inputs/outputs when needed.

**Comment by cmr** [comment]
I see. Yes, it should just be removed.

**Comment by cmr** [comment]
One potential issue is that there is no well-defined Fortran ABI... I feel uncomfortable about hardcoding the ABI assumptions.

**Comment by IvanUkhov** [comment]
Are you referring to name mangling? If so, we can create clean aliases (like just remove the trailing underscores) for the functions and use those in the code. Later on we can have feature flags or what not to set those aliases to the names that make sense to the compiler at hand.

**Comment by cmr** [comment]
Not the name mangling, but rather how arguments are passed.

**Comment by IvanUkhov** [comment]
How about having something intermediate like [this](https://github.com/stainless-steel/blas/blob/master/src/metal.rs)?

**Comment by cmr** [comment]
Yeah, might as well. Yay lots of extra boilerplate!

**Comment by bluss** [comment]
Hi, there is inconsistent information on cblas out there (I'm not sure what's correct).

This for example suggests that cblas does not allocate / copy / reorder inputs: http://stackoverflow.com/questions/32445741/does-mkl-optimize-cblas-for-major-order

**Comment by IvanUkhov** [comment]
@bluss, thanks for the feedback! Yeah, it’s a bit controversial. What happens under the hood is up to the particular implementation of BLAS/LAPACK at hand. Intel probably has two versions of each of the functions that take the layout parameter so that one doesn’t hit any computational overhead. I’m not sure how it’s done in OpenBLAS. Perhaps @xianyi could help us resolve this quandary.

Since you’ve revived this conversation, do you have any particular suggestions in mind? Would you like to see the C functions in this crate as well? Or?

P.S. The discussion [here](https://github.com/stainless-steel/blas-sys/issues/10) is also relevant.

Regards,
Ivan

**Comment by cmr** [comment]
There's still the issue of "is the fortran abi compatible with the c abi", that is unresolved. right now we just hope for the best, since the abis are compatible when using gfortran.

**Comment by bluss** [comment]
I'm looking at alternatives, since I was using the `rblas` crate. I am not going to use this crate I realized, since it uses `&[f32]` (slices) and I need a raw pointer interface, so I'm looking at either cblas bindings in rblas or blas-sys.

`ndarray` has a lot of work to do; and since it decided that its default ordering is row major, it needs cblas I think (and to find out which implementations handle it without copying).

**Comment by cmr** [comment]
The FORTRAN interface handles both row-major and column-major, the layout is controlled via arguments. cblas merely specializes that interface. IIRC netlib uses this to determine loop order, but otherwise does no transpositions, in-place or otherwise. Not sure how OpenBLAS compares on that regard, since I haven't spent the time studying its implementation, but I imagine it's the same or similar.

Note that the primary difference between this crate and blas-sys is very small, functionality-wise. In the past, I spent some considerable time trying to design an interface that allowed for very high-level usage by having a lot of the layout concerns hidden in a structure and providing traits for the operations. I also tried modeling it in the type system. Both experiments ultimately faltered because of lack of time and because I tried to handle every situation, of which there are many. The remnants of one of those experiments can be found here: https://github.com/stainless-steel/blas/blob/06d07d2c791abc16f1f9b20c1ced02025686d3b2/src/lib.rs

What are your requirements? I haven't investigated ndarray yet.

**Comment by cmr** [comment]
Also, note the extensions functions available in high-performance implementations: ?imatcopy allows for various in-place transformations, including transposition.

**Comment by IvanUkhov** [comment]
@bluss, it’d indeed be nice to have a look at the requirements that you have. Perhaps there’s a prominent use case that the crate is not currently covering and should be improved. I’m curious to know why you need raw pointers. It seems to me that the point of this kind of wrappers is to deliver the end user from messing with raw types.

**Comment by bluss** [comment]
@cmr That's interesting. The rblas crate is very similar, and I had a dream that I could only expose rblas-wrappers and it would be done. That first attempt just looks like this: [ndarray::blas](http://bluss.github.io/rust-ndarray/master/ndarray/blas/index.html)

ndarray is foremost an n-dimensional array, and unfortunately that also means it supports arbitrary striding schemes, so the first goal is just to use blas for matrix multiplication regardless if inputs are both row major, both col major, or in the fallback case, are any other layout at all.

To supply the necessary glue code to handle the odd cases, I think ndarray wants to wrap the operations themselves instead of just providing wrapper types to its matrices. It even wants to handle the error cases where the arrays are too large to handle with blas (dimension > c_int, not very likely).

So I think I just need cblas bindings. I have those too in `rblas`, haven't used them directly yet.

@IvanUkhov ndarray is not an end user but will wrap operations itself. It doesn't use slices to hold its data since an array view might have arbitrary stride, for example a column view from a 4 x 4 row major matrix, with have a pointer to the first element and a stride of for example 4.  If you consider mutable array views (exist in ndarray), it's not possible to give each column each a mutable slice of their data (this is aliasing).

**Comment by bluss** [comment]
What do you think is a good definitive doc to BLAS? For some reason I got the impression that two read only matrix inputs to `dgemm` may not overlap, but now I can't find where I read that (and I kind of doubt this restriction).

**Comment by cmr** [comment]
@bluss I typically used the documentation generated from netlib: http://www.netlib.org/lapack/explore-html/modules.html

Of course, it requires being able to understand FORTRAN and intimate familiarity with the operations they describe, but is otherwise IMO quite nice. Chicken Scheme has some higher-level documentation of some BLAS things in their FFI, and IIRC Julia also has some stuff but I never looked at it besides noting its existence.

**Comment by cmr** [comment]
I personally found rblas deeply unsatisfying from an API perspective, which is why I spent so much time trying to create a better interface that would be possible to enforce some invariants at the type-level, but I think it's futile. Very few people actually want that level of detail, and just want a numpy-for-Rust.

**Comment by IvanUkhov** [comment]
The documentation that @cmr mentioned was my primary source of information as well.

**Comment by IvanUkhov** [comment]
@cmr, perhaps the C interface is worth providing in `blas-sys`, `blas`, `lapack-sys`, and `lapack` so that people have a choice. I’m guessing `cblas_` and `LAPACKE_` functions are rather popular in some circles, especially among those with C/C++ backgrounds. What do you think?

**Comment by cmr** [comment]
Seems reasonable.

**Comment by IvanUkhov** [comment]
I close this in favor of #15.

**Comment by IvanUkhov** [comment]
@bluss, I was skimming over the [official description](http://www.netlib.org/lapack/lapacke.html#_array_arguments) of LAPACKE and came across the following lines:

> Note that using row-major ordering may require more memory and time than column-major ordering, because the routine must transpose the row-major order to the column-major order required by the underlying LAPACK routine.

Though “may” doesn’t enforce anything.

**Comment by bluss** [comment]
Netlib seems to be the implementation that doesn't implement a row-major friendly version of cblas too. I guess it's expected that implementations differ.

**Comment by cmr** [comment]
It's also the reference implementation, I think most deployments end up using IMKL or OpenBLAS or something tuned to platform they are on anyway.

**Comment by xianyi** [comment]
In OpenBLAS BLAS level, we didn't copy the matrix and transpose the row-major order to column-major.
